# Generated by Django 5.0.1 on 2024-01-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0002_country_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="country",
        ),
    ]
