# Generated by Django 5.0 on 2024-01-06 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplane', '0001_initial'),
        ('airport', '0001_initial'),
        ('luggage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplane.airplane')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_airport', to='airport.airport')),
                ('luggage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='luggage.luggage')),
                ('source_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_airport', to='airport.airport')),
            ],
        ),
    ]
