# Generated by Django 5.0 on 2024-01-07 08:29

from django.db import migrations

def load_initial_data(apps, schema_editor):
    role_model = apps.get_model('role', 'Role')
    role_model.objects.create(
        name = "Admin"
    )
    role_model.objects.create(
        name = "Reader"
    )
    role_model.objects.create(
        name = "Writer"
    )
    role_model.objects.create(
        name = "Owner"
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
