# Generated by Django 5.0 on 2024-01-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='flights',
            field=models.ManyToManyField(to='flight.flight'),
        ),
    ]
