# Generated by Django 5.0 on 2024-01-11 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('ticket', '0002_ticket_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='taxes',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
